"use strict";
// ゲーム難易度を変えるときは、ここだけを調整してください。
const CONFIG={playMs:30000,bottleSpeed:.24,bottleSpeedRamp:5,dropDurationMs:850,shotCooldownMs:260,maxDrops:3,eyeOpenMs:2000,blinkCloseMs:150,eyeClosedMs:100,blinkOpenMs:150,blinkJitter:.12,pupilWidth:.038,irisWidth:.085,eyeWidth:.225};
const c=document.querySelector("#game"),x=c.getContext("2d"),screens=Object.fromEntries(["start","countdown","result"].map(id=>[id,document.getElementById(id)]));
const n=document.querySelector("#countdownNumber"),s={mode:"start",score:0,attempts:0,successes:0,last:0,bx:.5,dir:1,blink:0,open:2000,drops:[],lastShot:0,redness:.88,message:null,particles:[],started:0};
let audioCtx=null,bgmTimer=null,bgmStep=0;
function audio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();return audioCtx}
function tone(freq,duration=.12,type="sine",volume=.06,delay=0){const a=audio(),t=a.currentTime+delay,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(a.destination);o.start(t);o.stop(t+duration+.02)}
function startBgm(){audio();if(bgmTimer)return;const melody=[262,330,392,330,294,349,440,349];const play=()=>{tone(melody[bgmStep++%melody.length],.24,"triangle",.025);tone(melody[(bgmStep+2)%melody.length]/2,.32,"sine",.012)};play();bgmTimer=setInterval(play,380)}
function stopBgm(){if(bgmTimer){clearInterval(bgmTimer);bgmTimer=null}}
function sound(kind){if(kind==="shot")tone(660,.08,"sine",.055);if(kind==="PERFECT!"){tone(660,.14,"square",.06);tone(880,.22,"square",.05,.1)}if(kind==="VERY GOOD!"){tone(587,.13,"triangle",.06);tone(740,.18,"triangle",.045,.08)}if(kind==="GOOD!")tone(523,.16,"triangle",.05);if(kind==="MISS")tone(180,.22,"sawtooth",.04);if(kind==="CLOSE!")tone(130,.17,"square",.045)}
function resize(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;x.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);resize();
function show(name){Object.values(screens).forEach(e=>e.classList.remove("active"));if(name)screens[name].classList.add("active")}
function openLength(){return CONFIG.eyeOpenMs*(1+(Math.random()*2-1)*CONFIG.blinkJitter)}
function eye(){let p=s.blink;if(p<s.open)return 1;p-=s.open;if(p<CONFIG.blinkCloseMs)return 1-p/CONFIG.blinkCloseMs;p-=CONFIG.blinkCloseMs;if(p<CONFIG.eyeClosedMs)return 0;return(p-CONFIG.eyeClosedMs)/CONFIG.blinkOpenMs}
function tickBlink(dt){s.blink+=dt;const total=s.open+CONFIG.blinkCloseMs+CONFIG.eyeClosedMs+CONFIG.blinkOpenMs;if(s.blink>=total){s.blink=0;s.open=openLength()}}
function countdown(){startBgm();s.mode="countdown";show("countdown");let v=3;n.textContent=v;tone(440,.1,"triangle",.04);const i=setInterval(()=>{v--;n.textContent=v||"GO!";tone(v?440:880,.1,"triangle",.04);if(v<0){clearInterval(i);begin()}},800)}
function begin(){Object.assign(s,{mode:"play",score:0,attempts:0,successes:0,bx:.5,dir:1,blink:0,open:openLength(),drops:[],lastShot:0,redness:.88,message:null,particles:[],started:performance.now()});show()}
function finish(){if(s.mode!=="play")return;s.mode="result";s.drops=[];stopBgm();tone(s.redness<=.05?784:196,.35,"triangle",.06);document.querySelector("#resultMessage").textContent=s.redness<=.05?"目が潤った":"目の疲れがとれなかった";document.querySelector("#resultScore").textContent=s.score;document.querySelector("#resultAttempts").textContent=s.attempts;document.querySelector("#resultRate").textContent=s.attempts?Math.round(s.successes/s.attempts*100)+"%":"0%";show("result")}
function shoot(){const now=performance.now();if(s.mode!=="play"||s.drops.length>=CONFIG.maxDrops||now-s.lastShot<CONFIG.shotCooldownMs)return;s.lastShot=now;s.attempts++;s.drops.push({px:s.bx,t:0,out:null,impact:0});sound("shot")}
c.addEventListener("pointerdown",e=>{e.preventDefault();shoot()});document.querySelector("#startButton").onclick=countdown;document.querySelector("#retryButton").onclick=countdown;
function hit(d){const distance=Math.abs(d.px-.5),opened=eye()>.72;if(!opened)d.out="CLOSE!";else if(distance<=CONFIG.pupilWidth)d.out="PERFECT!";else if(distance<=CONFIG.irisWidth)d.out="VERY GOOD!";else if(distance<=CONFIG.eyeWidth)d.out="GOOD!";else d.out="MISS";const points={"PERFECT!":10,"VERY GOOD!":5,"GOOD!":1,"MISS":-5,"CLOSE!":-5}[d.out];const success=points>0;s.score+=points;if(success){s.successes++;s.redness=Math.max(0,s.redness+({"PERFECT!":-.20,"VERY GOOD!":-.11,"GOOD!":-.045}[d.out]));}sound(d.out);s.message={text:`${d.out} ${points>0?"+":""}${points}`,age:0,color:d.out==="PERFECT!"?"#f04e48":d.out==="VERY GOOD!"?"#e87b32":d.out==="GOOD!"?"#278a70":d.out==="CLOSE!"?"#7454a5":"#34566e"};if(success){const count=d.out==="PERFECT!"?13:7;for(let i=0;i<count;i++)s.particles.push({px:d.px,py:.74,vx:(Math.random()-.5)*.34,vy:-Math.random()*.35,age:0})}}
function update(dt,now){if(s.mode!=="play")return;const played=now-s.started;if(played>=CONFIG.playMs)return finish();const speed=CONFIG.bottleSpeed*(1+(CONFIG.bottleSpeedRamp-1)*played/CONFIG.playMs);s.bx+=s.dir*speed*dt/1000;if(s.bx>.87||s.bx<.13){s.bx=Math.max(.13,Math.min(.87,s.bx));s.dir*=-1}tickBlink(dt);s.drops.forEach(d=>{d.t+=dt;if(!d.out&&d.t>=CONFIG.dropDurationMs)hit(d);if(d.out)d.impact+=dt});s.drops=s.drops.filter(d=>!d.out||d.impact<=580);if(s.message&&(s.message.age+=dt)>650)s.message=null;s.particles=s.particles.filter(p=>(p.age+=dt)<600)}
function el(a,b,rx,ry,col){x.fillStyle=col;x.beginPath();x.ellipse(a,b,rx,ry,0,0,Math.PI*2);x.fill()}
function draw(now){const w=c.clientWidth,h=c.clientHeight;x.clearRect(0,0,w,h);const bg=x.createLinearGradient(0,0,0,h);bg.addColorStop(0,"#75d9ea");bg.addColorStop(1,"#d3f5bd");x.fillStyle=bg;x.fillRect(0,0,w,h);x.fillStyle="#17344b";x.font="900 20px sans-serif";x.fillText("スコア "+s.score,20,38);x.textAlign="right";x.fillText("のこり "+Math.max(0,Math.ceil((CONFIG.playMs-(now-s.started))/1000)),w-20,38);x.textAlign="left";
const bx=s.bx*w,by=h*.18;x.save();x.translate(bx,by);x.rotate(s.dir*.13);x.fillStyle="#fff";x.strokeStyle="#277892";x.lineWidth=4;x.beginPath();x.roundRect(-34,-42,68,72,16);x.fill();x.stroke();x.fillStyle="#53c8dc";x.fillRect(-23,-26,46,42);x.fillStyle="#17455a";x.font="900 12px sans-serif";x.textAlign="center";x.fillText("めぐすり",0,0);x.fillStyle="#e6f8ff";x.beginPath();x.moveTo(-18,30);x.lineTo(18,30);x.lineTo(11,51);x.lineTo(-11,51);x.closePath();x.fill();x.stroke();x.fillStyle="#277892";x.beginPath();x.arc(0,51,11,0,Math.PI);x.fill();x.restore();x.textAlign="left";
const fy=h*.81,fw=w*.78,fh=h*.30;el(w/2,fy,fw/2,fh/2,"#ffd2af");const ey=h*.755,a=eye(),rx=w*CONFIG.eyeWidth,mry=h*.065,ry=Math.max(2,mry*a),sclera=`rgb(255,${Math.round(255-70*s.redness)},${Math.round(255-70*s.redness)})`;x.fillStyle=sclera;x.strokeStyle="#193b51";x.lineWidth=5;x.beginPath();x.ellipse(w/2,ey,rx,ry,0,0,Math.PI*2);x.fill();x.stroke();if(a>.08){el(w/2,ey,ry*.72,ry*.72,"#456f88");el(w/2,ey,ry*.35,ry*.35,"#172e43");el(w/2+ry*.15,ey-ry*.2,ry*.11,ry*.11,"#fff")}if(a<.96){let cover=mry*(1-a);x.fillStyle="#ffd2af";x.fillRect(w/2-rx-5,ey-mry-4,rx*2+10,cover);x.fillRect(w/2-rx-5,ey+mry-cover+4,rx*2+10,cover)}
s.drops.forEach(d=>{const p=Math.min(1,d.t/CONFIG.dropDurationMs);let yy=by+62+(ey-by-66)*p;if(d.out==="MISS")yy+=d.impact/580*h*.14;if(d.out==="CLOSE!")yy-=Math.sin(d.impact/580*Math.PI)*18;el(d.px*w,yy,10,15,"#249ee2");el(d.px*w-3,yy-5,2.5,4,"#eaffff")});s.particles.forEach(p=>{let t=p.age/600;el((p.px+p.vx*t)*w,(p.py+p.vy*t+.22*t*t)*h,4*(1-t),4*(1-t),"#fff")});if(s.message){const m=s.message;x.globalAlpha=1-m.age/650;x.fillStyle=m.color;x.font="900 32px sans-serif";x.textAlign="center";x.fillText(m.text,w/2,h*.57-m.age*.04);x.globalAlpha=1;x.textAlign="left"}}
function loop(now){const dt=Math.min(33,now-(s.last||now));s.last=now;update(dt,now);draw(now);requestAnimationFrame(loop)}requestAnimationFrame(loop);
